#!/bin/sh
#---------------------------------------------------------------------
# CSE 131 Reduced-C Compiler Project
# Copyright (C) 2008-2015 Garo Bournoutian and Rick Ord
# University of California, San Diego
#---------------------------------------------------------------------

java -cp $CLASSPATH:bin RC $*
